name: flutter_settings_ui
description: Fork of settings_ui. Create native settings for Flutter app in minutes.
version: 2.0.0
homepage: https://github.com/yako-dev/flutter-settings-ui

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
